/**********
Copyright 2024 Xidian University
Author: 2024 Bo Li
Modified: 2024/06/27  Bo Li
Refered to NgSPICE Res/Cap related file
**********/
#include "ngspice/ngspice.h"
#include "ngspice/devdefs.h"
#include "fefet1def.h"
#include "ngspice/suffix.h"

IFparm FEFET1pTable[] = { /* parameters */
   IOPAU("ic_p",         FECAP1_IC,              IF_REAL, "Initial fe-capacitor polarization"), 
   IOPAU("area",        	  FECAP1_AREA,           	IF_REAL, "Device area"),

   IOP( "l",   FEFET1_L,      IF_REAL   , "Length"),
   IOP( "w",   FEFET1_W,      IF_REAL   , "Width"),
   IOP( "m",   FEFET1_M,      IF_REAL   , "Separate Parallel multiplier"),
   IOP( "nf",  FEFET1_NF,     IF_REAL   , "Number of fingers"),
   IOP( "sa",  FEFET1_SA,     IF_REAL   , "distance between  OD edge to poly of one side "),
   IOP( "sb",  FEFET1_SB,     IF_REAL   , "distance between  OD edge to poly of the other side"),
   IOP( "sd",  FEFET1_SD,     IF_REAL   , "distance between neighbour fingers"),
   IOP( "sca",  FEFET1_SCA,     IF_REAL   , "Integral of the first distribution function for scattered well dopant"),
   IOP( "scb",  FEFET1_SCB,     IF_REAL   , "Integral of the second distribution function for scattered well dopant"),
   IOP( "scc",  FEFET1_SCC,     IF_REAL   , "Integral of the third distribution function for scattered well dopant"),
   IOP( "sc",   FEFET1_SC,    IF_REAL    , "Distance to a single well edge "),
   IOP( "min",  FEFET1_MIN,   IF_INTEGER , "Minimize either D or S"),
   IOP( "ad",  FEFET1_AD,     IF_REAL   , "Drain area"),
   IOP( "as",  FEFET1_AS,     IF_REAL   , "Source area"),
   IOP( "pd",  FEFET1_PD,     IF_REAL   , "Drain perimeter"),
   IOP( "ps",  FEFET1_PS,     IF_REAL   , "Source perimeter"),
   IOP( "nrd", FEFET1_NRD,    IF_REAL   , "Number of squares in drain"),
   IOP( "nrs", FEFET1_NRS,    IF_REAL   , "Number of squares in source"),
   IOP( "off", FEFET1_OFF,    IF_FLAG   , "Device is initially off"),
   IOP( "rbdb", FEFET1_RBDB,  IF_REAL   , "Body resistance"),
   IOP( "rbsb", FEFET1_RBSB,  IF_REAL   , "Body resistance"),
   IOP( "rbpb", FEFET1_RBPB,  IF_REAL   , "Body resistance"),
   IOP( "rbps", FEFET1_RBPS,  IF_REAL   , "Body resistance"),
   IOP( "rbpd", FEFET1_RBPD,  IF_REAL   , "Body resistance"),
   IOP( "delvto", FEFET1_DELVTO,  IF_REAL   , "Zero bias threshold voltage variation"),
   IOPR( "delvt0", FEFET1_DELVTO,  IF_REAL   , "Zero bias threshold voltage variation"),
   IOP( "xgw",  FEFET1_XGW, IF_REAL, "Distance from gate contact center to device edge"),
   IOP( "ngcon", FEFET1_NGCON, IF_REAL, "Number of gate contacts"),


   IOP( "trnqsmod", FEFET1_TRNQSMOD, IF_INTEGER, "Transient NQS model selector"),
   IOP( "acnqsmod", FEFET1_ACNQSMOD, IF_INTEGER, "AC NQS model selector"),
   IOP( "rbodymod", FEFET1_RBODYMOD, IF_INTEGER, "Distributed body R model selector"),
   IOP( "rgatemod", FEFET1_RGATEMOD, IF_INTEGER, "Gate resistance model selector"),
   IOP( "geomod", FEFET1_GEOMOD, IF_INTEGER, "Geometry dependent parasitics model selector"),
   IOP( "rgeomod", FEFET1_RGEOMOD, IF_INTEGER, "S/D resistance and contact model selector"),
   IP( "ic",  FEFET1_IC,     IF_REALVEC , "Vector of DS,GS,BS initial voltages"),
   OP( "gmbs",         FEFET1_GMBS,       IF_REAL,    "Gmb"),
   OP( "gm",           FEFET1_GM,         IF_REAL,    "Gm"),
   OP( "gds",          FEFET1_GDS,        IF_REAL,    "Gds"),
   OP( "vdsat",        FEFET1_VDSAT,      IF_REAL,    "Vdsat"),
   OP( "vth",          FEFET1_VON,        IF_REAL,    "Vth"),
   OP( "id",           FEFET1_CD,         IF_REAL,    "Ids"),
   OP( "ibd",          FEFET1_CBD,        IF_REAL,    "Ibd"),
   OP( "ibs",          FEFET1_CBS,        IF_REAL,    "Ibs"),
   OP( "gbd",          FEFET1_GBD,        IF_REAL,    "gbd"),
   OP( "gbs",          FEFET1_GBS,        IF_REAL,    "gbs"),
   OP( "isub",         FEFET1_CSUB,       IF_REAL,    "Isub"),
   OP( "igidl",        FEFET1_IGIDL,      IF_REAL,    "Igidl"),
   OP( "igisl",        FEFET1_IGISL,      IF_REAL,    "Igisl"),
   OP( "igs",          FEFET1_IGS,        IF_REAL,    "Igs"),
   OP( "igd",          FEFET1_IGD,        IF_REAL,    "Igd"),
   OP( "igb",          FEFET1_IGB,        IF_REAL,    "Igb"),
   OP( "igcs",         FEFET1_IGCS,       IF_REAL,    "Igcs"),
   OP( "igcd",         FEFET1_IGCD,       IF_REAL,    "Igcd"),
   OP( "vbs",          FEFET1_VBS,        IF_REAL,    "Vbs"),
   OP( "vgs",          FEFET1_VGS,        IF_REAL,    "Vgs"),
   OP( "vds",          FEFET1_VDS,        IF_REAL,    "Vds"),
   OP( "cgg",         FEFET1_CGGB,       IF_REAL,    "Cggb"),
   OP( "cgs",         FEFET1_CGSB,       IF_REAL,    "Cgsb"),
   OP( "cgd",         FEFET1_CGDB,       IF_REAL,    "Cgdb"),
   OP( "cbg",         FEFET1_CBGB,       IF_REAL,    "Cbgb"),
   OP( "cbd",         FEFET1_CBDB,       IF_REAL,    "Cbdb"),
   OP( "cbs",         FEFET1_CBSB,       IF_REAL,    "Cbsb"),
   OP( "cdg",         FEFET1_CDGB,       IF_REAL,    "Cdgb"),
   OP( "cdd",         FEFET1_CDDB,       IF_REAL,    "Cddb"),
   OP( "cds",         FEFET1_CDSB,       IF_REAL,    "Cdsb"),
   OP( "csg",         FEFET1_CSGB,       IF_REAL,    "Csgb"),
   OP( "csd",         FEFET1_CSDB,       IF_REAL,    "Csdb"),
   OP( "css",         FEFET1_CSSB,       IF_REAL,    "Cssb"),
   OP( "cgb",         FEFET1_CGBB,       IF_REAL,    "Cgbb"),
   OP( "cdb",         FEFET1_CDBB,       IF_REAL,    "Cdbb"),
   OP( "csb",         FEFET1_CSBB,       IF_REAL,    "Csbb"),
   OP( "cbb",         FEFET1_CBBB,       IF_REAL,    "Cbbb"),
   OP( "capbd",       FEFET1_CAPBD,      IF_REAL,    "Capbd"),
   OP( "capbs",       FEFET1_CAPBS,      IF_REAL,    "Capbs"),
   OP( "qg",          FEFET1_QG,         IF_REAL,    "Qgate"),
   OP( "qb",          FEFET1_QB,         IF_REAL,    "Qbulk"),
   OP( "qd",          FEFET1_QD,         IF_REAL,    "Qdrain"),
   OP( "qs",          FEFET1_QS,         IF_REAL,    "Qsource"),
   OP( "qinv",        FEFET1_QINV,       IF_REAL,    "Qinversion"),
   OP( "qdef",        FEFET1_QDEF,       IF_REAL,    "Qdef"),
   OP( "gcrg",        FEFET1_GCRG,       IF_REAL,    "Gcrg"),
   OP( "gtau",        FEFET1_GTAU,       IF_REAL,    "Gtau"),
};

IFparm FEFET1mPTable[] = { /* model parameters */
   IOP("Ec",	      FECAP1_MOD_Ec,		IF_REAL,		"fecapacitor model parameter Ec"), 
   IOP("Ps",	      FECAP1_MOD_Ps,		IF_REAL,		"fecapacitor model parameter Pr"), 
   IOP("rho",	      FECAP1_MOD_Rho,		IF_REAL,		"fecapacitor model parameter Rho"), 
   IOP("alpha",	  FECAP1_MOD_Alpha,		IF_REAL,		"fecapacitor model parameter Alpha"), 
   IOP("beta",	      FECAP1_MOD_Beta,		IF_REAL,		"fecapacitor model parameter Beta"), 
   IOP("gamma",	  FECAP1_MOD_Gamma,		IF_REAL,		"fecapacitor model parameter Gamma"), 	
   IOP("thick",	  FECAP1_MOD_Thickness,	IF_REAL,	

   IOP( "capmod", FEFET1_MOD_CAPMOD, IF_INTEGER, "Capacitance model selector"),
   IOP( "diomod", FEFET1_MOD_DIOMOD, IF_INTEGER, "Diode IV model selector"),
   IOP( "rdsmod", FEFET1_MOD_RDSMOD, IF_INTEGER, "Bias-dependent S/D resistance model selector"),
   IOP( "trnqsmod", FEFET1_MOD_TRNQSMOD, IF_INTEGER, "Transient NQS model selector"),
   IOP( "acnqsmod", FEFET1_MOD_ACNQSMOD, IF_INTEGER, "AC NQS model selector"),
   IOP( "mobmod", FEFET1_MOD_MOBMOD, IF_INTEGER, "Mobility model selector"),
   IOP( "rbodymod", FEFET1_MOD_RBODYMOD, IF_INTEGER, "Distributed body R model selector"),
   IOP( "rgatemod", FEFET1_MOD_RGATEMOD, IF_INTEGER, "Gate R model selector"),
   IOP( "permod", FEFET1_MOD_PERMOD, IF_INTEGER, "Pd and Ps model selector"),
   IOP( "geomod", FEFET1_MOD_GEOMOD, IF_INTEGER, "Geometry dependent parasitics model selector"),
   IOP( "rgeomod", FEFET1_MOD_RGEOMOD, IF_INTEGER, "S/D resistance and contact model selector"),
   IOP( "fnoimod", FEFET1_MOD_FNOIMOD, IF_INTEGER, "Flicker noise model selector"),
   IOP( "tnoimod", FEFET1_MOD_TNOIMOD, IF_INTEGER, "Thermal noise model selector"),
   IOP( "igcmod", FEFET1_MOD_IGCMOD, IF_INTEGER, "Gate-to-channel Ig model selector"),
   IOP( "igbmod", FEFET1_MOD_IGBMOD, IF_INTEGER, "Gate-to-body Ig model selector"),
   IOP( "tempmod", FEFET1_MOD_TEMPMOD, IF_INTEGER, "Temperature model selector"),
   IOP( "paramchk", FEFET1_MOD_PARAMCHK, IF_INTEGER, "Model parameter checking selector"),
   IOP( "binunit", FEFET1_MOD_BINUNIT, IF_INTEGER, "Bin  unit  selector"),
   IOP( "version", FEFET1_MOD_VERSION, IF_STRING, "parameter for model version"),
   IOP( "toxe", FEFET1_MOD_TOXE, IF_REAL, "Electrical gate oxide thickness in meters"),
   IOP( "toxp", FEFET1_MOD_TOXP, IF_REAL, "Physical gate oxide thickness in meters"),
   IOP( "toxm", FEFET1_MOD_TOXM, IF_REAL, "Gate oxide thickness at which parameters are extracted"),
   IOP( "toxref", FEFET1_MOD_TOXREF, IF_REAL, "Target tox value"),
   IOP( "dtox", FEFET1_MOD_DTOX, IF_REAL, "Defined as (toxe - toxp) "),
   IOP( "epsrox", FEFET1_MOD_EPSROX, IF_REAL, "Dielectric constant of the gate oxide relative to vacuum"),
   IOP( "cdsc", FEFET1_MOD_CDSC, IF_REAL, "Drain/Source and channel coupling capacitance"),
   IOP( "cdscb", FEFET1_MOD_CDSCB, IF_REAL, "Body-bias dependence of cdsc"), 
   IOP( "cdscd", FEFET1_MOD_CDSCD, IF_REAL, "Drain-bias dependence of cdsc"), 
   IOP( "cit", FEFET1_MOD_CIT, IF_REAL, "Interface state capacitance"),
   IOP( "nfactor", FEFET1_MOD_NFACTOR, IF_REAL, "Subthreshold swing Coefficient"),
   IOP( "xj", FEFET1_MOD_XJ, IF_REAL, "Junction depth in meters"),
   IOP( "vsat", FEFET1_MOD_VSAT, IF_REAL, "Saturation velocity at tnom"),
   IOP( "at", FEFET1_MOD_AT, IF_REAL, "Temperature coefficient of vsat"),
   IOP( "a0", FEFET1_MOD_A0, IF_REAL, "Non-uniform depletion width effect coefficient."), 
   IOP( "ags", FEFET1_MOD_AGS, IF_REAL, "Gate bias  coefficient of Abulk."), 
   IOP( "a1", FEFET1_MOD_A1, IF_REAL, "Non-saturation effect coefficient"),
   IOP( "a2", FEFET1_MOD_A2, IF_REAL, "Non-saturation effect coefficient"),
   IOP( "keta", FEFET1_MOD_KETA, IF_REAL, "Body-bias coefficient of non-uniform depletion width effect."),
   IOP( "nsub", FEFET1_MOD_NSUB, IF_REAL, "Substrate doping concentration"),
   IOP( "ndep", FEFET1_MOD_NDEP, IF_REAL, "Channel doping concentration at the depletion edge"),
   IOP( "nsd", FEFET1_MOD_NSD, IF_REAL, "S/D doping concentration"),
   IOP( "phin", FEFET1_MOD_PHIN, IF_REAL, "Adjusting parameter for surface potential due to non-uniform vertical doping"),
   IOP( "ngate", FEFET1_MOD_NGATE, IF_REAL, "Poly-gate doping concentration"),
   IOP( "gamma1", FEFET1_MOD_GAMMA1, IF_REAL, "Vth body coefficient"),
   IOP( "gamma2", FEFET1_MOD_GAMMA2, IF_REAL, "Vth body coefficient"),
   IOP( "vbx", FEFET1_MOD_VBX, IF_REAL, "Vth transition body Voltage"),
   IOP( "vbm", FEFET1_MOD_VBM, IF_REAL, "Maximum body voltage"),

   IOP( "xt", FEFET1_MOD_XT, IF_REAL, "Doping depth"),
   IOP( "k1", FEFET1_MOD_K1, IF_REAL, "Bulk effect coefficient 1"),
   IOP( "kt1", FEFET1_MOD_KT1, IF_REAL, "Temperature coefficient of Vth"),
   IOP( "kt1l", FEFET1_MOD_KT1L, IF_REAL, "Temperature coefficient of Vth"),
   IOP( "kt2",  FEFET1_MOD_KT2, IF_REAL, "Body-coefficient of kt1"),
   IOP( "k2",   FEFET1_MOD_K2,  IF_REAL, "Bulk effect coefficient 2"),
   IOP( "k3",   FEFET1_MOD_K3,  IF_REAL, "Narrow width effect coefficient"),
   IOP( "k3b",  FEFET1_MOD_K3B, IF_REAL, "Body effect coefficient of k3"),
   IOP( "w0",   FEFET1_MOD_W0,  IF_REAL, "Narrow width effect parameter"),
   IOP( "dvtp0",  FEFET1_MOD_DVTP0, IF_REAL, "First parameter for Vth shift due to pocket"),
   IOP( "dvtp1",  FEFET1_MOD_DVTP1, IF_REAL, "Second parameter for Vth shift due to pocket"),
   IOP( "lpe0",  FEFET1_MOD_LPE0, IF_REAL, "Equivalent length of pocket region at zero bias"),
   IOP( "lpeb",  FEFET1_MOD_LPEB, IF_REAL, "Equivalent length of pocket region accounting for body bias"),
   IOP( "dvt0", FEFET1_MOD_DVT0, IF_REAL, "Short channel effect coeff. 0"),
   IOP( "dvt1", FEFET1_MOD_DVT1, IF_REAL, "Short channel effect coeff. 1"),
   IOP( "dvt2", FEFET1_MOD_DVT2, IF_REAL, "Short channel effect coeff. 2"),
   IOP( "dvt0w", FEFET1_MOD_DVT0W, IF_REAL, "Narrow Width coeff. 0"),
   IOP( "dvt1w", FEFET1_MOD_DVT1W, IF_REAL, "Narrow Width effect coeff. 1"),
   IOP( "dvt2w", FEFET1_MOD_DVT2W, IF_REAL, "Narrow Width effect coeff. 2"),
   IOP( "drout", FEFET1_MOD_DROUT, IF_REAL, "DIBL coefficient of output resistance"),
   IOP( "dsub", FEFET1_MOD_DSUB, IF_REAL, "DIBL coefficient in the subthreshold region"),
   IOP( "vth0", FEFET1_MOD_VTH0, IF_REAL,"Threshold voltage"),
   IOPR("vtho", FEFET1_MOD_VTH0, IF_REAL,"Threshold voltage"),
   IOP( "ua", FEFET1_MOD_UA, IF_REAL, "Linear gate dependence of mobility"),
   IOP( "ua1", FEFET1_MOD_UA1, IF_REAL, "Temperature coefficient of ua"),
   IOP( "ub", FEFET1_MOD_UB, IF_REAL, "Quadratic gate dependence of mobility"),
   IOP( "ub1", FEFET1_MOD_UB1, IF_REAL, "Temperature coefficient of ub"),
   IOP( "uc", FEFET1_MOD_UC, IF_REAL, "Body-bias dependence of mobility"),
   IOP( "uc1", FEFET1_MOD_UC1, IF_REAL, "Temperature coefficient of uc"),
   IOP( "ud", FEFET1_MOD_UD, IF_REAL, "Coulomb scattering factor of mobility"),
   IOP( "ud1", FEFET1_MOD_UD1, IF_REAL, "Temperature coefficient of ud"),
   IOP( "up", FEFET1_MOD_UP, IF_REAL, "Channel length linear factor of mobility"),
   IOP( "lp", FEFET1_MOD_LP, IF_REAL, "Channel length exponential factor of mobility"),
   IOP( "u0", FEFET1_MOD_U0, IF_REAL, "Low-field mobility at Tnom"),
   IOP( "eu", FEFET1_MOD_EU, IF_REAL, "Mobility exponent"),
   IOP( "ute", FEFET1_MOD_UTE, IF_REAL, "Temperature coefficient of mobility"),
   IOP( "voff", FEFET1_MOD_VOFF, IF_REAL, "Threshold voltage offset"),
   IOP( "minv", FEFET1_MOD_MINV, IF_REAL, "Fitting parameter for moderate invversion in Vgsteff"),
   IOP( "voffl", FEFET1_MOD_VOFFL, IF_REAL, "Length dependence parameter for Vth offset"),
   IOP( "tnom", FEFET1_MOD_TNOM, IF_REAL, "Parameter measurement temperature"),
   IOP( "cgso", FEFET1_MOD_CGSO, IF_REAL, "Gate-source overlap capacitance per width"),
   IOP( "cgdo", FEFET1_MOD_CGDO, IF_REAL, "Gate-drain overlap capacitance per width"),
   IOP( "cgbo", FEFET1_MOD_CGBO, IF_REAL, "Gate-bulk overlap capacitance per length"),
   IOP( "xpart", FEFET1_MOD_XPART, IF_REAL, "Channel charge partitioning"),
   IOP( "delta", FEFET1_MOD_DELTA, IF_REAL, "Effective Vds parameter"),
   IOP( "rsh", FEFET1_MOD_RSH, IF_REAL, "Source-drain sheet resistance"),
   IOP( "rdsw", FEFET1_MOD_RDSW, IF_REAL, "Source-drain resistance per width"),    
   IOP( "rdswmin", FEFET1_MOD_RDSWMIN, IF_REAL, "Source-drain resistance per width at high Vg"),
   IOP( "rsw", FEFET1_MOD_RSW, IF_REAL, "Source resistance per width"),
   IOP( "rdw", FEFET1_MOD_RDW, IF_REAL, "Drain resistance per width"),
   IOP( "rdwmin", FEFET1_MOD_RDWMIN, IF_REAL, "Drain resistance per width at high Vg"),
   IOP( "rswmin", FEFET1_MOD_RSWMIN, IF_REAL, "Source resistance per width at high Vg"),

   IOP( "prwg", FEFET1_MOD_PRWG, IF_REAL, "Gate-bias effect on parasitic resistance "),    
   IOP( "prwb", FEFET1_MOD_PRWB, IF_REAL, "Body-effect on parasitic resistance "),    

   IOP( "prt", FEFET1_MOD_PRT, IF_REAL, "Temperature coefficient of parasitic resistance "),    
   IOP( "eta0", FEFET1_MOD_ETA0, IF_REAL, "Subthreshold region DIBL coefficient"),
   IOP( "etab", FEFET1_MOD_ETAB, IF_REAL, "Subthreshold region DIBL coefficient"),
   IOP( "pclm", FEFET1_MOD_PCLM, IF_REAL, "Channel length modulation Coefficient"),
   IOP( "pdiblc1", FEFET1_MOD_PDIBL1, IF_REAL, "Drain-induced barrier lowering coefficient"),   
   IOP( "pdiblc2", FEFET1_MOD_PDIBL2, IF_REAL, "Drain-induced barrier lowering coefficient"),   
   IOP( "pdiblcb", FEFET1_MOD_PDIBLB, IF_REAL, "Body-effect on drain-induced barrier lowering"),   
   IOP( "fprout", FEFET1_MOD_FPROUT, IF_REAL, "Rout degradation coefficient for pocket devices"),
   IOP( "pdits", FEFET1_MOD_PDITS, IF_REAL, "Coefficient for drain-induced Vth shifts"),
   IOP( "pditsl", FEFET1_MOD_PDITSL, IF_REAL, "Length dependence of drain-induced Vth shifts"),
   IOP( "pditsd", FEFET1_MOD_PDITSD, IF_REAL, "Vds dependence of drain-induced Vth shifts"),
   IOP( "pscbe1", FEFET1_MOD_PSCBE1, IF_REAL, "Substrate current body-effect coefficient"),   
   IOP( "pscbe2", FEFET1_MOD_PSCBE2, IF_REAL, "Substrate current body-effect coefficient"),   
   IOP( "pvag", FEFET1_MOD_PVAG, IF_REAL, "Gate dependence of output resistance parameter"),   

   IOP( "jss", FEFET1_MOD_JSS, IF_REAL, "Bottom source junction reverse saturation current density"),
   IOP( "jsws", FEFET1_MOD_JSWS, IF_REAL, "Isolation edge sidewall source junction reverse saturation current density"),
   IOP( "jswgs", FEFET1_MOD_JSWGS, IF_REAL, "Gate edge source junction reverse saturation current density"),
   IOP( "pbs", FEFET1_MOD_PBS, IF_REAL, "Source junction built-in potential"),
   IOP( "njs", FEFET1_MOD_NJS, IF_REAL, "Source junction emission coefficient"),
   IOP( "xtis", FEFET1_MOD_XTIS, IF_REAL, "Source junction current temperature exponent"),
   IOP( "mjs", FEFET1_MOD_MJS, IF_REAL, "Source bottom junction capacitance grading coefficient"),
   IOP( "pbsws", FEFET1_MOD_PBSWS, IF_REAL, "Source sidewall junction capacitance built in potential"),
   IOP( "mjsws", FEFET1_MOD_MJSWS, IF_REAL, "Source sidewall junction capacitance grading coefficient"),
   IOP( "pbswgs", FEFET1_MOD_PBSWGS, IF_REAL, "Source (gate side) sidewall junction capacitance built in potential"),
   IOP( "mjswgs", FEFET1_MOD_MJSWGS, IF_REAL, "Source (gate side) sidewall junction capacitance grading coefficient"),
   IOP( "cjs", FEFET1_MOD_CJS, IF_REAL, "Source bottom junction capacitance per unit area"),
   IOP( "cjsws", FEFET1_MOD_CJSWS, IF_REAL, "Source sidewall junction capacitance per unit periphery"),
   IOP( "cjswgs", FEFET1_MOD_CJSWGS, IF_REAL, "Source (gate side) sidewall junction capacitance per unit width"),

   IOP( "jsd", FEFET1_MOD_JSD, IF_REAL, "Bottom drain junction reverse saturation current density"),
   IOP( "jswd", FEFET1_MOD_JSWD, IF_REAL, "Isolation edge sidewall drain junction reverse saturation current density"),
   IOP( "jswgd", FEFET1_MOD_JSWGD, IF_REAL, "Gate edge drain junction reverse saturation current density"),
   IOP( "pbd", FEFET1_MOD_PBD, IF_REAL, "Drain junction built-in potential"),
   IOP( "njd", FEFET1_MOD_NJD, IF_REAL, "Drain junction emission coefficient"),
   IOP( "xtid", FEFET1_MOD_XTID, IF_REAL, "Drainjunction current temperature exponent"),
   IOP( "mjd", FEFET1_MOD_MJD, IF_REAL, "Drain bottom junction capacitance grading coefficient"),
   IOP( "pbswd", FEFET1_MOD_PBSWD, IF_REAL, "Drain sidewall junction capacitance built in potential"),
   IOP( "mjswd", FEFET1_MOD_MJSWD, IF_REAL, "Drain sidewall junction capacitance grading coefficient"),
   IOP( "pbswgd", FEFET1_MOD_PBSWGD, IF_REAL, "Drain (gate side) sidewall junction capacitance built in potential"),
   IOP( "mjswgd", FEFET1_MOD_MJSWGD, IF_REAL, "Drain (gate side) sidewall junction capacitance grading coefficient"),
   IOP( "cjd", FEFET1_MOD_CJD, IF_REAL, "Drain bottom junction capacitance per unit area"),
   IOP( "cjswd", FEFET1_MOD_CJSWD, IF_REAL, "Drain sidewall junction capacitance per unit periphery"),
   IOP( "cjswgd", FEFET1_MOD_CJSWGD, IF_REAL, "Drain (gate side) sidewall junction capacitance per unit width"),

   IOP( "vfbcv", FEFET1_MOD_VFBCV, IF_REAL, "Flat Band Voltage parameter for capmod=0 only"),
   IOP( "vfb", FEFET1_MOD_VFB, IF_REAL, "Flat Band Voltage"),
   IOP( "tpb", FEFET1_MOD_TPB, IF_REAL, "Temperature coefficient of pb"),
   IOP( "tcj", FEFET1_MOD_TCJ, IF_REAL, "Temperature coefficient of cj"),
   IOP( "tpbsw", FEFET1_MOD_TPBSW, IF_REAL, "Temperature coefficient of pbsw"),
   IOP( "tcjsw", FEFET1_MOD_TCJSW, IF_REAL, "Temperature coefficient of cjsw"),
   IOP( "tpbswg", FEFET1_MOD_TPBSWG, IF_REAL, "Temperature coefficient of pbswg"),
   IOP( "tcjswg", FEFET1_MOD_TCJSWG, IF_REAL, "Temperature coefficient of cjswg"),
   IOP( "acde", FEFET1_MOD_ACDE, IF_REAL, "Exponential coefficient for finite charge thickness"),
   IOP( "moin", FEFET1_MOD_MOIN, IF_REAL, "Coefficient for gate-bias dependent surface potential"),
   IOP( "noff", FEFET1_MOD_NOFF, IF_REAL, "C-V turn-on/off parameter"),
   IOP( "voffcv", FEFET1_MOD_VOFFCV, IF_REAL, "C-V lateral-shift parameter"),
   IOP( "dmcg", FEFET1_MOD_DMCG, IF_REAL, "Distance of Mid-Contact to Gate edge"),
   IOP( "dmci", FEFET1_MOD_DMCI, IF_REAL, "Distance of Mid-Contact to Isolation"),
   IOP( "dmdg", FEFET1_MOD_DMDG, IF_REAL, "Distance of Mid-Diffusion to Gate edge"),
   IOP( "dmcgt", FEFET1_MOD_DMCGT, IF_REAL, "Distance of Mid-Contact to Gate edge in Test structures"),
   IOP( "xgw",  FEFET1_MOD_XGW, IF_REAL, "Distance from gate contact center to device edge"),
   IOP( "xgl",  FEFET1_MOD_XGL, IF_REAL, "Variation in Ldrawn"),
   IOP( "rshg", FEFET1_MOD_RSHG, IF_REAL, "Gate sheet resistance"),
   IOP( "ngcon", FEFET1_MOD_NGCON, IF_REAL, "Number of gate contacts"),
   IOP( "xrcrg1",  FEFET1_MOD_XRCRG1, IF_REAL, "First fitting parameter the bias-dependent Rg"),
   IOP( "xrcrg2",  FEFET1_MOD_XRCRG2, IF_REAL, "Second fitting parameter the bias-dependent Rg"),
   IOP( "lambda",  FEFET1_MOD_LAMBDA, IF_REAL, " Velocity overshoot parameter"),
   IOP( "vtl",      FEFET1_MOD_VTL,     IF_REAL, " thermal velocity"),
   IOP( "lc",     FEFET1_MOD_LC,     IF_REAL, " back scattering parameter"),
   IOP( "xn",     FEFET1_MOD_XN,     IF_REAL, " back scattering parameter"),
   IOP( "vfbsdoff",     FEFET1_MOD_VFBSDOFF,     IF_REAL, "S/D flatband voltage offset"),
   IOP( "tvfbsdoff",     FEFET1_MOD_TVFBSDOFF,     IF_REAL, "Temperature parameter for vfbsdoff"),
   IOP( "tvoff",     FEFET1_MOD_TVOFF,     IF_REAL, "Temperature parameter for voff"),

   IOP( "lintnoi", FEFET1_MOD_LINTNOI, IF_REAL, "lint offset for noise calculation"),
   IOP( "lint", FEFET1_MOD_LINT, IF_REAL, "Length reduction parameter"),
   IOP( "ll",   FEFET1_MOD_LL, IF_REAL, "Length reduction parameter"),
   IOP( "llc",  FEFET1_MOD_LLC, IF_REAL, "Length reduction parameter for CV"),
   IOP( "lln",  FEFET1_MOD_LLN, IF_REAL, "Length reduction parameter"),
   IOP( "lw",   FEFET1_MOD_LW,  IF_REAL, "Length reduction parameter"),
   IOP( "lwc",  FEFET1_MOD_LWC, IF_REAL, "Length reduction parameter for CV"),
   IOP( "lwn",  FEFET1_MOD_LWN, IF_REAL, "Length reduction parameter"),
   IOP( "lwl",  FEFET1_MOD_LWL, IF_REAL, "Length reduction parameter"),
   IOP( "lwlc", FEFET1_MOD_LWLC, IF_REAL, "Length reduction parameter for CV"),
   IOP( "lmin", FEFET1_MOD_LMIN, IF_REAL, "Minimum length for the model"),
   IOP( "lmax", FEFET1_MOD_LMAX, IF_REAL, "Maximum length for the model"),

   IOP( "wr",   FEFET1_MOD_WR, IF_REAL, "Width dependence of rds"),
   IOP( "wint", FEFET1_MOD_WINT, IF_REAL, "Width reduction parameter"),
   IOP( "dwg",  FEFET1_MOD_DWG, IF_REAL, "Width reduction parameter"),
   IOP( "dwb",  FEFET1_MOD_DWB, IF_REAL, "Width reduction parameter"),

   IOP( "wl",   FEFET1_MOD_WL, IF_REAL, "Width reduction parameter"),
   IOP( "wlc",  FEFET1_MOD_WLC, IF_REAL, "Width reduction parameter for CV"),
   IOP( "wln",  FEFET1_MOD_WLN, IF_REAL, "Width reduction parameter"),
   IOP( "ww",   FEFET1_MOD_WW, IF_REAL, "Width reduction parameter"),
   IOP( "wwc",  FEFET1_MOD_WWC, IF_REAL, "Width reduction parameter for CV"),
   IOP( "wwn",  FEFET1_MOD_WWN, IF_REAL, "Width reduction parameter"),
   IOP( "wwl",  FEFET1_MOD_WWL, IF_REAL, "Width reduction parameter"),
   IOP( "wwlc", FEFET1_MOD_WWLC, IF_REAL, "Width reduction parameter for CV"),
   IOP( "wmin", FEFET1_MOD_WMIN, IF_REAL, "Minimum width for the model"),
   IOP( "wmax", FEFET1_MOD_WMAX, IF_REAL, "Maximum width for the model"),

   IOP( "b0",  FEFET1_MOD_B0, IF_REAL, "Abulk narrow width parameter"),
   IOP( "b1",  FEFET1_MOD_B1, IF_REAL, "Abulk narrow width parameter"),

   IOP( "cgsl", FEFET1_MOD_CGSL, IF_REAL, "New C-V model parameter"),
   IOP( "cgdl", FEFET1_MOD_CGDL, IF_REAL, "New C-V model parameter"),
   IOP( "ckappas", FEFET1_MOD_CKAPPAS, IF_REAL, "S/G overlap C-V parameter "),
   IOP( "ckappad", FEFET1_MOD_CKAPPAD, IF_REAL, "D/G overlap C-V parameter"),
   IOP( "cf",  FEFET1_MOD_CF, IF_REAL, "Fringe capacitance parameter"),
   IOP( "clc", FEFET1_MOD_CLC, IF_REAL, "Vdsat parameter for C-V model"),
   IOP( "cle", FEFET1_MOD_CLE, IF_REAL, "Vdsat parameter for C-V model"),
   IOP( "dwc", FEFET1_MOD_DWC, IF_REAL, "Delta W for C-V model"),
   IOP( "dlc", FEFET1_MOD_DLC, IF_REAL, "Delta L for C-V model"),
   IOP( "xw", FEFET1_MOD_XW, IF_REAL, "W offset for channel width due to mask/etch effect"),
   IOP( "xl", FEFET1_MOD_XL, IF_REAL, "L offset for channel length due to mask/etch effect"),
   IOP( "dlcig", FEFET1_MOD_DLCIG, IF_REAL, "Delta L for Ig model"),
   IOP( "dwj", FEFET1_MOD_DWJ, IF_REAL, "Delta W for S/D junctions"),

   IOP( "alpha0", FEFET1_MOD_ALPHA0, IF_REAL, "substrate current model parameter"),
   IOP( "alpha1", FEFET1_MOD_ALPHA1, IF_REAL, "substrate current model parameter"),
   IOP( "beta0", FEFET1_MOD_BETA0, IF_REAL, "substrate current model parameter"),

   IOP( "agidl", FEFET1_MOD_AGIDL, IF_REAL, "Pre-exponential constant for GIDL"),
   IOP( "bgidl", FEFET1_MOD_BGIDL, IF_REAL, "Exponential constant for GIDL"),
   IOP( "cgidl", FEFET1_MOD_CGIDL, IF_REAL, "Parameter for body-bias dependence of GIDL"),
   IOP( "egidl", FEFET1_MOD_EGIDL, IF_REAL, "Fitting parameter for Bandbending"),
   IOP( "aigc", FEFET1_MOD_AIGC, IF_REAL, "Parameter for Igc"),
   IOP( "bigc", FEFET1_MOD_BIGC, IF_REAL, "Parameter for Igc"),
   IOP( "cigc", FEFET1_MOD_CIGC, IF_REAL, "Parameter for Igc"),
   IOP( "aigsd", FEFET1_MOD_AIGSD, IF_REAL, "Parameter for Igs,d"),
   IOP( "bigsd", FEFET1_MOD_BIGSD, IF_REAL, "Parameter for Igs,d"),
   IOP( "cigsd", FEFET1_MOD_CIGSD, IF_REAL, "Parameter for Igs,d"),
   IOP( "aigbacc", FEFET1_MOD_AIGBACC, IF_REAL, "Parameter for Igb"),
   IOP( "bigbacc", FEFET1_MOD_BIGBACC, IF_REAL, "Parameter for Igb"),
   IOP( "cigbacc", FEFET1_MOD_CIGBACC, IF_REAL, "Parameter for Igb"),
   IOP( "aigbinv", FEFET1_MOD_AIGBINV, IF_REAL, "Parameter for Igb"),
   IOP( "bigbinv", FEFET1_MOD_BIGBINV, IF_REAL, "Parameter for Igb"),
   IOP( "cigbinv", FEFET1_MOD_CIGBINV, IF_REAL, "Parameter for Igb"),
   IOP( "nigc", FEFET1_MOD_NIGC, IF_REAL, "Parameter for Igc slope"),
   IOP( "nigbinv", FEFET1_MOD_NIGBINV, IF_REAL, "Parameter for Igbinv slope"),
   IOP( "nigbacc", FEFET1_MOD_NIGBACC, IF_REAL, "Parameter for Igbacc slope"),
   IOP( "ntox", FEFET1_MOD_NTOX, IF_REAL, "Exponent for Tox ratio"),
   IOP( "eigbinv", FEFET1_MOD_EIGBINV, IF_REAL, "Parameter for the Si bandgap for Igbinv"),
   IOP( "pigcd", FEFET1_MOD_PIGCD, IF_REAL, "Parameter for Igc partition"),
   IOP( "poxedge", FEFET1_MOD_POXEDGE, IF_REAL, "Factor for the gate edge Tox"),

   IOP( "ijthdfwd", FEFET1_MOD_IJTHDFWD, IF_REAL, "Forward drain diode forward limiting current"),
   IOP( "ijthsfwd", FEFET1_MOD_IJTHSFWD, IF_REAL, "Forward source diode forward limiting current"),
   IOP( "ijthdrev", FEFET1_MOD_IJTHDREV, IF_REAL, "Reverse drain diode forward limiting current"),
   IOP( "ijthsrev", FEFET1_MOD_IJTHSREV, IF_REAL, "Reverse source diode forward limiting current"),
   IOP( "xjbvd", FEFET1_MOD_XJBVD, IF_REAL, "Fitting parameter for drain diode breakdown current"),
   IOP( "xjbvs", FEFET1_MOD_XJBVS, IF_REAL, "Fitting parameter for source diode breakdown current"),
   IOP( "bvd", FEFET1_MOD_BVD, IF_REAL, "Drain diode breakdown voltage"),
   IOP( "bvs", FEFET1_MOD_BVS, IF_REAL, "Source diode breakdown voltage"),

   IOP( "jtss", FEFET1_MOD_JTSS, IF_REAL, "Source bottom trap-assisted saturation current density"),
   IOP( "jtsd", FEFET1_MOD_JTSD, IF_REAL, "Drain bottom trap-assisted saturation current density"),
   IOP( "jtssws", FEFET1_MOD_JTSSWS, IF_REAL, "Source STI sidewall trap-assisted saturation current density"),
   IOP( "jtsswd", FEFET1_MOD_JTSSWD, IF_REAL, "Drain STI sidewall trap-assisted saturation current density"),
   IOP( "jtsswgs", FEFET1_MOD_JTSSWGS, IF_REAL, "Source gate-edge sidewall trap-assisted saturation current density"),
   IOP( "jtsswgd", FEFET1_MOD_JTSSWGD, IF_REAL, "Drain gate-edge sidewall trap-assisted saturation current density"),
   IOP( "njts", FEFET1_MOD_NJTS, IF_REAL, "Non-ideality factor for bottom junction"),
   IOP( "njtssw", FEFET1_MOD_NJTSSW, IF_REAL, "Non-ideality factor for STI sidewall junction"),
   IOP( "njtsswg", FEFET1_MOD_NJTSSWG, IF_REAL, "Non-ideality factor for gate-edge sidewall junction"),
   IOP( "xtss", FEFET1_MOD_XTSS, IF_REAL, "Power dependence of JTSS on temperature"),
   IOP( "xtsd", FEFET1_MOD_XTSD, IF_REAL, "Power dependence of JTSD on temperature"),
   IOP( "xtssws", FEFET1_MOD_XTSSWS, IF_REAL, "Power dependence of JTSSWS on temperature"),
   IOP( "xtsswd", FEFET1_MOD_XTSSWD, IF_REAL, "Power dependence of JTSSWD on temperature"),
   IOP( "xtsswgs", FEFET1_MOD_XTSSWGS, IF_REAL, "Power dependence of JTSSWGS on temperature"),
   IOP( "xtsswgd", FEFET1_MOD_XTSSWGD, IF_REAL, "Power dependence of JTSSWGD on temperature"),
   IOP( "tnjts", FEFET1_MOD_TNJTS, IF_REAL, "Temperature coefficient for NJTS"),
   IOP( "tnjtssw", FEFET1_MOD_TNJTSSW, IF_REAL, "Temperature coefficient for NJTSSW"),
   IOP( "tnjtsswg", FEFET1_MOD_TNJTSSWG, IF_REAL, "Temperature coefficient for NJTSSWG"),
   IOP( "vtss", FEFET1_MOD_VTSS, IF_REAL, "Source bottom trap-assisted voltage dependent parameter"),
   IOP( "vtsd", FEFET1_MOD_VTSD, IF_REAL, "Drain bottom trap-assisted voltage dependent parameter"),
   IOP( "vtssws", FEFET1_MOD_VTSSWS, IF_REAL, "Source STI sidewall trap-assisted voltage dependent parameter"),
   IOP( "vtsswd", FEFET1_MOD_VTSSWD, IF_REAL, "Drain STI sidewall trap-assisted voltage dependent parameter"),
   IOP( "vtsswgs", FEFET1_MOD_VTSSWGS, IF_REAL, "Source gate-edge sidewall trap-assisted voltage dependent parameter"),
   IOP( "vtsswgd", FEFET1_MOD_VTSSWGD, IF_REAL, "Drain gate-edge sidewall trap-assisted voltage dependent parameter"),

   IOP( "gbmin", FEFET1_MOD_GBMIN, IF_REAL, "Minimum body conductance"),
   IOP( "rbdb", FEFET1_MOD_RBDB, IF_REAL, "Resistance between bNode and dbNode"),
   IOP( "rbpb", FEFET1_MOD_RBPB, IF_REAL, "Resistance between bNodePrime and bNode"),
   IOP( "rbsb", FEFET1_MOD_RBSB, IF_REAL, "Resistance between bNode and sbNode"),
   IOP( "rbps", FEFET1_MOD_RBPS, IF_REAL, "Resistance between bNodePrime and sbNode"),
   IOP( "rbpd", FEFET1_MOD_RBPD, IF_REAL, "Resistance between bNodePrime and bNode"),

   IOP( "rbps0",  FEFET1_MOD_RBPS0,   IF_REAL   , "Body resistance RBPS scaling"),
   IOP( "rbpsl",  FEFET1_MOD_RBPSL,   IF_REAL   , "Body resistance RBPS L scaling"),
   IOP( "rbpsw",  FEFET1_MOD_RBPSW,   IF_REAL   , "Body resistance RBPS W scaling"),
   IOP( "rbpsnf", FEFET1_MOD_RBPSNF,  IF_REAL   , "Body resistance RBPS NF scaling"),

   IOP( "rbpd0",  FEFET1_MOD_RBPD0,   IF_REAL   , "Body resistance RBPD scaling"),
   IOP( "rbpdl",  FEFET1_MOD_RBPDL,   IF_REAL   , "Body resistance RBPD L scaling"),
   IOP( "rbpdw",  FEFET1_MOD_RBPDW,   IF_REAL   , "Body resistance RBPD W scaling"),
   IOP( "rbpdnf", FEFET1_MOD_RBPDNF,  IF_REAL   , "Body resistance RBPD NF scaling"),

   IOP( "rbpbx0", FEFET1_MOD_RBPBX0,  IF_REAL   , "Body resistance RBPBX  scaling"),
   IOP( "rbpbxl", FEFET1_MOD_RBPBXL,  IF_REAL   , "Body resistance RBPBX L scaling"),
   IOP( "rbpbxw", FEFET1_MOD_RBPBXW,  IF_REAL   , "Body resistance RBPBX W scaling"),
   IOP( "rbpbxnf", FEFET1_MOD_RBPBXNF, IF_REAL   , "Body resistance RBPBX NF scaling"),
   IOP( "rbpby0", FEFET1_MOD_RBPBY0,  IF_REAL   , "Body resistance RBPBY  scaling"),
   IOP( "rbpbyl", FEFET1_MOD_RBPBYL,  IF_REAL   , "Body resistance RBPBY L scaling"),
   IOP( "rbpbyw", FEFET1_MOD_RBPBYW,  IF_REAL   , "Body resistance RBPBY W scaling"),
   IOP( "rbpbynf", FEFET1_MOD_RBPBYNF, IF_REAL   , "Body resistance RBPBY NF scaling"),

   IOP( "rbsbx0", FEFET1_MOD_RBSBX0,  IF_REAL   , "Body resistance RBSBX  scaling"),
   IOP( "rbsby0", FEFET1_MOD_RBSBY0,  IF_REAL   , "Body resistance RBSBY  scaling"),
   IOP( "rbdbx0", FEFET1_MOD_RBDBX0,  IF_REAL   , "Body resistance RBDBX  scaling"),
   IOP( "rbdby0", FEFET1_MOD_RBDBY0,  IF_REAL   , "Body resistance RBDBY  scaling"),

   IOP( "rbsdbxl",  FEFET1_MOD_RBSDBXL,   IF_REAL   , "Body resistance RBSDBX L scaling"),
   IOP( "rbsdbxw",  FEFET1_MOD_RBSDBXW,   IF_REAL   , "Body resistance RBSDBX W scaling"),
   IOP( "rbsdbxnf", FEFET1_MOD_RBSDBXNF,  IF_REAL   , "Body resistance RBSDBX NF scaling"),
   IOP( "rbsdbyl",  FEFET1_MOD_RBSDBYL,   IF_REAL   , "Body resistance RBSDBY L scaling"),
   IOP( "rbsdbyw",  FEFET1_MOD_RBSDBYW,   IF_REAL   , "Body resistance RBSDBY W scaling"),
   IOP( "rbsdbynf", FEFET1_MOD_RBSDBYNF,  IF_REAL   , "Body resistance RBSDBY NF scaling"),

   IOP( "lcdsc",  FEFET1_MOD_LCDSC, IF_REAL, "Length dependence of cdsc"),
   IOP( "lcdscb", FEFET1_MOD_LCDSCB, IF_REAL, "Length dependence of cdscb"),
   IOP( "lcdscd", FEFET1_MOD_LCDSCD, IF_REAL, "Length dependence of cdscd"),
   IOP( "lcit",   FEFET1_MOD_LCIT,  IF_REAL, "Length dependence of cit"),
   IOP( "lnfactor", FEFET1_MOD_LNFACTOR, IF_REAL, "Length dependence of nfactor"),
   IOP( "lxj", FEFET1_MOD_LXJ, IF_REAL, "Length dependence of xj"),
   IOP( "lvsat", FEFET1_MOD_LVSAT, IF_REAL, "Length dependence of vsat"),
   IOP( "lat", FEFET1_MOD_LAT, IF_REAL, "Length dependence of at"),
   IOP( "la0", FEFET1_MOD_LA0, IF_REAL, "Length dependence of a0"), 
   IOP( "lags", FEFET1_MOD_LAGS, IF_REAL, "Length dependence of ags"), 
   IOP( "la1", FEFET1_MOD_LA1, IF_REAL, "Length dependence of a1"),
   IOP( "la2", FEFET1_MOD_LA2, IF_REAL, "Length dependence of a2"),
   IOP( "lketa", FEFET1_MOD_LKETA, IF_REAL, "Length dependence of keta"),
   IOP( "lnsub", FEFET1_MOD_LNSUB, IF_REAL, "Length dependence of nsub"),
   IOP( "lndep",  FEFET1_MOD_LNDEP, IF_REAL, "Length dependence of ndep"),
   IOP( "lnsd",  FEFET1_MOD_LNSD, IF_REAL, "Length dependence of nsd"),
   IOP( "lphin", FEFET1_MOD_LPHIN, IF_REAL, "Length dependence of phin"),
   IOP( "lngate", FEFET1_MOD_LNGATE, IF_REAL, "Length dependence of ngate"),
   IOP( "lgamma1", FEFET1_MOD_LGAMMA1, IF_REAL, "Length dependence of gamma1"),
   IOP( "lgamma2", FEFET1_MOD_LGAMMA2, IF_REAL, "Length dependence of gamma2"),
   IOP( "lvbx", FEFET1_MOD_LVBX, IF_REAL, "Length dependence of vbx"),
   IOP( "lvbm", FEFET1_MOD_LVBM, IF_REAL, "Length dependence of vbm"),
   IOP( "lxt",  FEFET1_MOD_LXT,  IF_REAL, "Length dependence of xt"),
   IOP( "lk1",   FEFET1_MOD_LK1,  IF_REAL, "Length dependence of k1"),
   IOP( "lkt1",  FEFET1_MOD_LKT1, IF_REAL, "Length dependence of kt1"),
   IOP( "lkt1l", FEFET1_MOD_LKT1L, IF_REAL, "Length dependence of kt1l"),
   IOP( "lkt2",  FEFET1_MOD_LKT2, IF_REAL, "Length dependence of kt2"),
   IOP( "lk2",   FEFET1_MOD_LK2,  IF_REAL, "Length dependence of k2"),
   IOP( "lk3",   FEFET1_MOD_LK3,  IF_REAL, "Length dependence of k3"),
   IOP( "lk3b",  FEFET1_MOD_LK3B, IF_REAL, "Length dependence of k3b"),
   IOP( "lw0",   FEFET1_MOD_LW0,  IF_REAL, "Length dependence of w0"),
   IOP( "ldvtp0",  FEFET1_MOD_LDVTP0, IF_REAL, "Length dependence of dvtp0"),
   IOP( "ldvtp1",  FEFET1_MOD_LDVTP1, IF_REAL, "Length dependence of dvtp1"),
   IOP( "llpe0",  FEFET1_MOD_LLPE0, IF_REAL, "Length dependence of lpe0"),
   IOP( "llpeb",  FEFET1_MOD_LLPEB, IF_REAL, "Length dependence of lpeb"),
   IOP( "ldvt0", FEFET1_MOD_LDVT0, IF_REAL, "Length dependence of dvt0"),
   IOP( "ldvt1", FEFET1_MOD_LDVT1, IF_REAL, "Length dependence of dvt1"),
   IOP( "ldvt2", FEFET1_MOD_LDVT2, IF_REAL, "Length dependence of dvt2"),
   IOP( "ldvt0w", FEFET1_MOD_LDVT0W, IF_REAL, "Length dependence of dvt0w"),
   IOP( "ldvt1w", FEFET1_MOD_LDVT1W, IF_REAL, "Length dependence of dvt1w"),
   IOP( "ldvt2w", FEFET1_MOD_LDVT2W, IF_REAL, "Length dependence of dvt2w"),
   IOP( "ldrout", FEFET1_MOD_LDROUT, IF_REAL, "Length dependence of drout"),
   IOP( "ldsub", FEFET1_MOD_LDSUB, IF_REAL, "Length dependence of dsub"),
   IOP( "lvth0", FEFET1_MOD_LVTH0, IF_REAL,"Length dependence of vth0"),
   IOPR("lvtho", FEFET1_MOD_LVTH0, IF_REAL,"Length dependence of vtho"),
   IOP( "lua",  FEFET1_MOD_LUA, IF_REAL, "Length dependence of ua"),
   IOP( "lua1", FEFET1_MOD_LUA1, IF_REAL, "Length dependence of ua1"),
   IOP( "lub", FEFET1_MOD_LUB, IF_REAL, "Length dependence of ub"),
   IOP( "lub1", FEFET1_MOD_LUB1, IF_REAL, "Length dependence of ub1"),
   IOP( "luc",  FEFET1_MOD_LUC, IF_REAL, "Length dependence of uc"),
   IOP( "luc1", FEFET1_MOD_LUC1, IF_REAL, "Length dependence of uc1"),
   IOP( "lud",  FEFET1_MOD_LUD, IF_REAL, "Length dependence of ud"),
   IOP( "lud1", FEFET1_MOD_LUD1, IF_REAL, "Length dependence of ud1"),
   IOP( "lup",  FEFET1_MOD_LUP, IF_REAL, "Length dependence of up"),
   IOP( "llp",  FEFET1_MOD_LLP, IF_REAL, "Length dependence of lp"),
   IOP( "lu0",  FEFET1_MOD_LU0, IF_REAL, "Length dependence of u0"),
   IOP( "lute", FEFET1_MOD_LUTE, IF_REAL, "Length dependence of ute"),
   IOP( "lvoff", FEFET1_MOD_LVOFF, IF_REAL, "Length dependence of voff"),
   IOP( "lminv", FEFET1_MOD_LMINV, IF_REAL, "Length dependence of minv"),
   IOP( "ldelta", FEFET1_MOD_LDELTA, IF_REAL, "Length dependence of delta"),
   IOP( "lrdsw", FEFET1_MOD_LRDSW,  IF_REAL, "Length dependence of rdsw "),    
   IOP( "lrsw", FEFET1_MOD_LRSW, IF_REAL, "Length dependence of rsw"),
   IOP( "lrdw", FEFET1_MOD_LRDW, IF_REAL, "Length dependence of rdw"),

   IOP( "lprwg", FEFET1_MOD_LPRWG,  IF_REAL, "Length dependence of prwg "),    
   IOP( "lprwb", FEFET1_MOD_LPRWB,  IF_REAL, "Length dependence of prwb "),    

   IOP( "lprt", FEFET1_MOD_LPRT, IF_REAL, "Length dependence of prt "),    
   IOP( "leta0", FEFET1_MOD_LETA0, IF_REAL, "Length dependence of eta0"),   
   IOP( "letab", FEFET1_MOD_LETAB, IF_REAL, "Length dependence of etab"),   
   IOP( "lpclm", FEFET1_MOD_LPCLM, IF_REAL, "Length dependence of pclm"),   
   IOP( "lpdiblc1", FEFET1_MOD_LPDIBL1, IF_REAL, "Length dependence of pdiblc1"),   
   IOP( "lpdiblc2", FEFET1_MOD_LPDIBL2, IF_REAL, "Length dependence of pdiblc2"),   
   IOP( "lpdiblcb", FEFET1_MOD_LPDIBLB, IF_REAL, "Length dependence of pdiblcb"),   
   IOP( "lfprout", FEFET1_MOD_LFPROUT, IF_REAL, "Length dependence of pdiblcb"),
   IOP( "lpdits", FEFET1_MOD_LPDITS, IF_REAL, "Length dependence of pdits"),
   IOP( "lpditsd", FEFET1_MOD_LPDITSD, IF_REAL, "Length dependence of pditsd"),
   IOP( "lpscbe1",  FEFET1_MOD_LPSCBE1, IF_REAL, "Length dependence of pscbe1"),   
   IOP( "lpscbe2",  FEFET1_MOD_LPSCBE2, IF_REAL, "Length dependence of pscbe2"),   
   IOP( "lpvag", FEFET1_MOD_LPVAG, IF_REAL, "Length dependence of pvag"),   
   IOP( "lwr",  FEFET1_MOD_LWR, IF_REAL, "Length dependence of wr"),
   IOP( "ldwg", FEFET1_MOD_LDWG, IF_REAL, "Length dependence of dwg"),
   IOP( "ldwb", FEFET1_MOD_LDWB, IF_REAL, "Length dependence of dwb"),
   IOP( "lb0",  FEFET1_MOD_LB0, IF_REAL, "Length dependence of b0"),
   IOP( "lb1",  FEFET1_MOD_LB1, IF_REAL, "Length dependence of b1"),
   IOP( "lcgsl", FEFET1_MOD_LCGSL, IF_REAL, "Length dependence of cgsl"),
   IOP( "lcgdl", FEFET1_MOD_LCGDL, IF_REAL, "Length dependence of cgdl"),
   IOP( "lckappas", FEFET1_MOD_LCKAPPAS, IF_REAL, "Length dependence of ckappas"),
   IOP( "lckappad", FEFET1_MOD_LCKAPPAD, IF_REAL, "Length dependence of ckappad"),
   IOP( "lcf",  FEFET1_MOD_LCF,  IF_REAL, "Length dependence of cf"),
   IOP( "lclc", FEFET1_MOD_LCLC, IF_REAL, "Length dependence of clc"),
   IOP( "lcle", FEFET1_MOD_LCLE, IF_REAL, "Length dependence of cle"),
   IOP( "lalpha0", FEFET1_MOD_LALPHA0, IF_REAL, "Length dependence of alpha0"),
   IOP( "lalpha1", FEFET1_MOD_LALPHA1, IF_REAL, "Length dependence of alpha1"),
   IOP( "lbeta0", FEFET1_MOD_LBETA0, IF_REAL, "Length dependence of beta0"),

   IOP( "lagidl", FEFET1_MOD_LAGIDL, IF_REAL, "Length dependence of agidl"),
   IOP( "lbgidl", FEFET1_MOD_LBGIDL, IF_REAL, "Length dependence of bgidl"),
   IOP( "lcgidl", FEFET1_MOD_LCGIDL, IF_REAL, "Length dependence of cgidl"),
   IOP( "legidl", FEFET1_MOD_LEGIDL, IF_REAL, "Length dependence of egidl"),
   IOP( "laigc", FEFET1_MOD_LAIGC, IF_REAL, "Length dependence of aigc"),
   IOP( "lbigc", FEFET1_MOD_LBIGC, IF_REAL, "Length dependence of bigc"),
   IOP( "lcigc", FEFET1_MOD_LCIGC, IF_REAL, "Length dependence of cigc"),
   IOP( "laigsd", FEFET1_MOD_LAIGSD, IF_REAL, "Length dependence of aigsd"),
   IOP( "lbigsd", FEFET1_MOD_LBIGSD, IF_REAL, "Length dependence of bigsd"),
   IOP( "lcigsd", FEFET1_MOD_LCIGSD, IF_REAL, "Length dependence of cigsd"),
   IOP( "laigbacc", FEFET1_MOD_LAIGBACC, IF_REAL, "Length dependence of aigbacc"),
   IOP( "lbigbacc", FEFET1_MOD_LBIGBACC, IF_REAL, "Length dependence of bigbacc"),
   IOP( "lcigbacc", FEFET1_MOD_LCIGBACC, IF_REAL, "Length dependence of cigbacc"),
   IOP( "laigbinv", FEFET1_MOD_LAIGBINV, IF_REAL, "Length dependence of aigbinv"),
   IOP( "lbigbinv", FEFET1_MOD_LBIGBINV, IF_REAL, "Length dependence of bigbinv"),
   IOP( "lcigbinv", FEFET1_MOD_LCIGBINV, IF_REAL, "Length dependence of cigbinv"),
   IOP( "lnigc", FEFET1_MOD_LNIGC, IF_REAL, "Length dependence of nigc"),
   IOP( "lnigbinv", FEFET1_MOD_LNIGBINV, IF_REAL, "Length dependence of nigbinv"),
   IOP( "lnigbacc", FEFET1_MOD_LNIGBACC, IF_REAL, "Length dependence of nigbacc"),
   IOP( "lntox", FEFET1_MOD_LNTOX, IF_REAL, "Length dependence of ntox"),
   IOP( "leigbinv", FEFET1_MOD_LEIGBINV, IF_REAL, "Length dependence for eigbinv"),
   IOP( "lpigcd", FEFET1_MOD_LPIGCD, IF_REAL, "Length dependence for pigcd"),
   IOP( "lpoxedge", FEFET1_MOD_LPOXEDGE, IF_REAL, "Length dependence for poxedge"),

   IOP( "lvfbcv", FEFET1_MOD_LVFBCV, IF_REAL, "Length dependence of vfbcv"),
   IOP( "lvfb", FEFET1_MOD_LVFB, IF_REAL, "Length dependence of vfb"),
   IOP( "lacde", FEFET1_MOD_LACDE, IF_REAL, "Length dependence of acde"),
   IOP( "lmoin", FEFET1_MOD_LMOIN, IF_REAL, "Length dependence of moin"),
   IOP( "lnoff", FEFET1_MOD_LNOFF, IF_REAL, "Length dependence of noff"),
   IOP( "lvoffcv", FEFET1_MOD_LVOFFCV, IF_REAL, "Length dependence of voffcv"),
   IOP( "lxrcrg1",  FEFET1_MOD_LXRCRG1, IF_REAL, "Length dependence of xrcrg1"),
   IOP( "lxrcrg2",  FEFET1_MOD_LXRCRG2, IF_REAL, "Length dependence of xrcrg2"),
   IOP( "llambda",  FEFET1_MOD_LLAMBDA, IF_REAL, "Length dependence of lambda"),
   IOP( "lvtl",      FEFET1_MOD_LVTL,     IF_REAL, " Length dependence of vtl"),
   IOP( "lxn",     FEFET1_MOD_LXN,    IF_REAL, " Length dependence of xn"),
   IOP( "leu",  FEFET1_MOD_LEU, IF_REAL, " Length dependence of eu"),
   IOP( "lvfbsdoff",     FEFET1_MOD_LVFBSDOFF,     IF_REAL, "Length dependence of vfbsdoff"),
   IOP( "ltvfbsdoff",     FEFET1_MOD_LTVFBSDOFF,     IF_REAL, "Length dependence of tvfbsdoff"),
   IOP( "ltvoff",     FEFET1_MOD_LTVOFF,     IF_REAL, "Length dependence of tvoff"),

   IOP( "wcdsc",  FEFET1_MOD_WCDSC, IF_REAL, "Width dependence of cdsc"),
   IOP( "wcdscb", FEFET1_MOD_WCDSCB, IF_REAL, "Width dependence of cdscb"),  
   IOP( "wcdscd", FEFET1_MOD_WCDSCD, IF_REAL, "Width dependence of cdscd"),  
   IOP( "wcit",   FEFET1_MOD_WCIT,  IF_REAL, "Width dependence of cit"),
   IOP( "wnfactor", FEFET1_MOD_WNFACTOR, IF_REAL, "Width dependence of nfactor"),
   IOP( "wxj", FEFET1_MOD_WXJ, IF_REAL, "Width dependence of xj"),
   IOP( "wvsat", FEFET1_MOD_WVSAT, IF_REAL, "Width dependence of vsat"),
   IOP( "wat", FEFET1_MOD_WAT, IF_REAL, "Width dependence of at"),
   IOP( "wa0", FEFET1_MOD_WA0, IF_REAL, "Width dependence of a0"), 
   IOP( "wags", FEFET1_MOD_WAGS, IF_REAL, "Width dependence of ags"), 
   IOP( "wa1", FEFET1_MOD_WA1, IF_REAL, "Width dependence of a1"),
   IOP( "wa2", FEFET1_MOD_WA2, IF_REAL, "Width dependence of a2"),
   IOP( "wketa", FEFET1_MOD_WKETA, IF_REAL, "Width dependence of keta"),
   IOP( "wnsub", FEFET1_MOD_WNSUB, IF_REAL, "Width dependence of nsub"),
   IOP( "wndep",  FEFET1_MOD_WNDEP, IF_REAL, "Width dependence of ndep"),
   IOP( "wnsd",  FEFET1_MOD_WNSD, IF_REAL, "Width dependence of nsd"),
   IOP( "wphin", FEFET1_MOD_WPHIN, IF_REAL, "Width dependence of phin"),
   IOP( "wngate", FEFET1_MOD_WNGATE, IF_REAL, "Width dependence of ngate"),
   IOP( "wgamma1", FEFET1_MOD_WGAMMA1, IF_REAL, "Width dependence of gamma1"),
   IOP( "wgamma2", FEFET1_MOD_WGAMMA2, IF_REAL, "Width dependence of gamma2"),
   IOP( "wvbx", FEFET1_MOD_WVBX, IF_REAL, "Width dependence of vbx"),
   IOP( "wvbm", FEFET1_MOD_WVBM, IF_REAL, "Width dependence of vbm"),
   IOP( "wxt",  FEFET1_MOD_WXT,  IF_REAL, "Width dependence of xt"),
   IOP( "wk1",   FEFET1_MOD_WK1,  IF_REAL, "Width dependence of k1"),
   IOP( "wkt1",  FEFET1_MOD_WKT1, IF_REAL, "Width dependence of kt1"),
   IOP( "wkt1l", FEFET1_MOD_WKT1L, IF_REAL, "Width dependence of kt1l"),
   IOP( "wkt2",  FEFET1_MOD_WKT2, IF_REAL, "Width dependence of kt2"),
   IOP( "wk2",   FEFET1_MOD_WK2,  IF_REAL, "Width dependence of k2"),
   IOP( "wk3",   FEFET1_MOD_WK3,  IF_REAL, "Width dependence of k3"),
   IOP( "wk3b",  FEFET1_MOD_WK3B, IF_REAL, "Width dependence of k3b"),
   IOP( "ww0",   FEFET1_MOD_WW0,  IF_REAL, "Width dependence of w0"),
   IOP( "wdvtp0",  FEFET1_MOD_WDVTP0, IF_REAL, "Width dependence of dvtp0"),
   IOP( "wdvtp1",  FEFET1_MOD_WDVTP1, IF_REAL, "Width dependence of dvtp1"),
   IOP( "wlpe0",  FEFET1_MOD_WLPE0, IF_REAL, "Width dependence of lpe0"),
   IOP( "wlpeb",  FEFET1_MOD_WLPEB, IF_REAL, "Width dependence of lpeb"),
   IOP( "wdvt0", FEFET1_MOD_WDVT0, IF_REAL, "Width dependence of dvt0"),
   IOP( "wdvt1", FEFET1_MOD_WDVT1, IF_REAL, "Width dependence of dvt1"),
   IOP( "wdvt2", FEFET1_MOD_WDVT2, IF_REAL, "Width dependence of dvt2"),
   IOP( "wdvt0w", FEFET1_MOD_WDVT0W, IF_REAL, "Width dependence of dvt0w"),
   IOP( "wdvt1w", FEFET1_MOD_WDVT1W, IF_REAL, "Width dependence of dvt1w"),
   IOP( "wdvt2w", FEFET1_MOD_WDVT2W, IF_REAL, "Width dependence of dvt2w"),
   IOP( "wdrout", FEFET1_MOD_WDROUT, IF_REAL, "Width dependence of drout"),
   IOP( "wdsub", FEFET1_MOD_WDSUB, IF_REAL, "Width dependence of dsub"),
   IOP( "wvth0", FEFET1_MOD_WVTH0, IF_REAL,"Width dependence of vth0"),
   IOPR("wvtho", FEFET1_MOD_WVTH0, IF_REAL,"Width dependence of vtho"),
   IOP( "wua",  FEFET1_MOD_WUA, IF_REAL, "Width dependence of ua"),
   IOP( "wua1", FEFET1_MOD_WUA1, IF_REAL, "Width dependence of ua1"),
   IOP( "wub", FEFET1_MOD_WUB, IF_REAL, "Width dependence of ub"),
   IOP( "wub1", FEFET1_MOD_WUB1, IF_REAL, "Width dependence of ub1"),
   IOP( "wuc",  FEFET1_MOD_WUC, IF_REAL, "Width dependence of uc"),
   IOP( "wuc1", FEFET1_MOD_WUC1, IF_REAL, "Width dependence of uc1"),
   IOP( "wud",  FEFET1_MOD_WUD, IF_REAL, "Width dependence of ud"),
   IOP( "wud1", FEFET1_MOD_WUD1, IF_REAL, "Width dependence of ud1"),
   IOP( "wup",  FEFET1_MOD_WUP, IF_REAL, "Width dependence of up"),
   IOP( "wlp",  FEFET1_MOD_WLP, IF_REAL, "Width dependence of lp"),
   IOP( "wu0",  FEFET1_MOD_WU0, IF_REAL, "Width dependence of u0"),
   IOP( "wute", FEFET1_MOD_WUTE, IF_REAL, "Width dependence of ute"),
   IOP( "wvoff", FEFET1_MOD_WVOFF, IF_REAL, "Width dependence of voff"),
   IOP( "wminv", FEFET1_MOD_WMINV, IF_REAL, "Width dependence of minv"),
   IOP( "wdelta", FEFET1_MOD_WDELTA, IF_REAL, "Width dependence of delta"),
   IOP( "wrdsw", FEFET1_MOD_WRDSW,  IF_REAL, "Width dependence of rdsw "),
   IOP( "wrsw", FEFET1_MOD_WRSW, IF_REAL, "Width dependence of rsw"),
   IOP( "wrdw", FEFET1_MOD_WRDW, IF_REAL, "Width dependence of rdw"),

   IOP( "wprwg", FEFET1_MOD_WPRWG,  IF_REAL, "Width dependence of prwg "),
   IOP( "wprwb", FEFET1_MOD_WPRWB,  IF_REAL, "Width dependence of prwb "),

   IOP( "wprt", FEFET1_MOD_WPRT, IF_REAL, "Width dependence of prt"),
   IOP( "weta0", FEFET1_MOD_WETA0, IF_REAL, "Width dependence of eta0"),   
   IOP( "wetab", FEFET1_MOD_WETAB, IF_REAL, "Width dependence of etab"),   
   IOP( "wpclm", FEFET1_MOD_WPCLM, IF_REAL, "Width dependence of pclm"),   
   IOP( "wpdiblc1", FEFET1_MOD_WPDIBL1, IF_REAL, "Width dependence of pdiblc1"),   
   IOP( "wpdiblc2", FEFET1_MOD_WPDIBL2, IF_REAL, "Width dependence of pdiblc2"),   
   IOP( "wpdiblcb", FEFET1_MOD_WPDIBLB, IF_REAL, "Width dependence of pdiblcb"),   
   IOP( "wfprout", FEFET1_MOD_WFPROUT, IF_REAL, "Width dependence of pdiblcb"),
   IOP( "wpdits", FEFET1_MOD_WPDITS, IF_REAL, "Width dependence of pdits"),
   IOP( "wpditsd", FEFET1_MOD_WPDITSD, IF_REAL, "Width dependence of pditsd"),
   IOP( "wpscbe1",  FEFET1_MOD_WPSCBE1, IF_REAL, "Width dependence of pscbe1"),   
   IOP( "wpscbe2",  FEFET1_MOD_WPSCBE2, IF_REAL, "Width dependence of pscbe2"),   
   IOP( "wpvag", FEFET1_MOD_WPVAG, IF_REAL, "Width dependence of pvag"),   
   IOP( "wwr",  FEFET1_MOD_WWR, IF_REAL, "Width dependence of wr"),
   IOP( "wdwg", FEFET1_MOD_WDWG, IF_REAL, "Width dependence of dwg"),
   IOP( "wdwb", FEFET1_MOD_WDWB, IF_REAL, "Width dependence of dwb"),
   IOP( "wb0",  FEFET1_MOD_WB0, IF_REAL, "Width dependence of b0"),
   IOP( "wb1",  FEFET1_MOD_WB1, IF_REAL, "Width dependence of b1"),
   IOP( "wcgsl", FEFET1_MOD_WCGSL, IF_REAL, "Width dependence of cgsl"),
   IOP( "wcgdl", FEFET1_MOD_WCGDL, IF_REAL, "Width dependence of cgdl"),
   IOP( "wckappas", FEFET1_MOD_WCKAPPAS, IF_REAL, "Width dependence of ckappas"),
   IOP( "wckappad", FEFET1_MOD_WCKAPPAD, IF_REAL, "Width dependence of ckappad"),
   IOP( "wcf",  FEFET1_MOD_WCF,  IF_REAL, "Width dependence of cf"),
   IOP( "wclc", FEFET1_MOD_WCLC, IF_REAL, "Width dependence of clc"),
   IOP( "wcle", FEFET1_MOD_WCLE, IF_REAL, "Width dependence of cle"),
   IOP( "walpha0", FEFET1_MOD_WALPHA0, IF_REAL, "Width dependence of alpha0"),
   IOP( "walpha1", FEFET1_MOD_WALPHA1, IF_REAL, "Width dependence of alpha1"),
   IOP( "wbeta0", FEFET1_MOD_WBETA0, IF_REAL, "Width dependence of beta0"),

   IOP( "wagidl", FEFET1_MOD_WAGIDL, IF_REAL, "Width dependence of agidl"),
   IOP( "wbgidl", FEFET1_MOD_WBGIDL, IF_REAL, "Width dependence of bgidl"),
   IOP( "wcgidl", FEFET1_MOD_WCGIDL, IF_REAL, "Width dependence of cgidl"),
   IOP( "wegidl", FEFET1_MOD_WEGIDL, IF_REAL, "Width dependence of egidl"),
   IOP( "waigc", FEFET1_MOD_WAIGC, IF_REAL, "Width dependence of aigc"),
   IOP( "wbigc", FEFET1_MOD_WBIGC, IF_REAL, "Width dependence of bigc"),
   IOP( "wcigc", FEFET1_MOD_WCIGC, IF_REAL, "Width dependence of cigc"),
   IOP( "waigsd", FEFET1_MOD_WAIGSD, IF_REAL, "Width dependence of aigsd"),
   IOP( "wbigsd", FEFET1_MOD_WBIGSD, IF_REAL, "Width dependence of bigsd"),
   IOP( "wcigsd", FEFET1_MOD_WCIGSD, IF_REAL, "Width dependence of cigsd"),
   IOP( "waigbacc", FEFET1_MOD_WAIGBACC, IF_REAL, "Width dependence of aigbacc"),
   IOP( "wbigbacc", FEFET1_MOD_WBIGBACC, IF_REAL, "Width dependence of bigbacc"),
   IOP( "wcigbacc", FEFET1_MOD_WCIGBACC, IF_REAL, "Width dependence of cigbacc"),
   IOP( "waigbinv", FEFET1_MOD_WAIGBINV, IF_REAL, "Width dependence of aigbinv"),
   IOP( "wbigbinv", FEFET1_MOD_WBIGBINV, IF_REAL, "Width dependence of bigbinv"),
   IOP( "wcigbinv", FEFET1_MOD_WCIGBINV, IF_REAL, "Width dependence of cigbinv"),
   IOP( "wnigc", FEFET1_MOD_WNIGC, IF_REAL, "Width dependence of nigc"),
   IOP( "wnigbinv", FEFET1_MOD_WNIGBINV, IF_REAL, "Width dependence of nigbinv"),
   IOP( "wnigbacc", FEFET1_MOD_WNIGBACC, IF_REAL, "Width dependence of nigbacc"),
   IOP( "wntox", FEFET1_MOD_WNTOX, IF_REAL, "Width dependence of ntox"),
   IOP( "weigbinv", FEFET1_MOD_WEIGBINV, IF_REAL, "Width dependence for eigbinv"),
   IOP( "wpigcd", FEFET1_MOD_WPIGCD, IF_REAL, "Width dependence for pigcd"),
   IOP( "wpoxedge", FEFET1_MOD_WPOXEDGE, IF_REAL, "Width dependence for poxedge"),
   IOP( "wvfbcv", FEFET1_MOD_WVFBCV, IF_REAL, "Width dependence of vfbcv"),
   IOP( "wvfb", FEFET1_MOD_WVFB, IF_REAL, "Width dependence of vfb"),
   IOP( "wacde", FEFET1_MOD_WACDE, IF_REAL, "Width dependence of acde"),
   IOP( "wmoin", FEFET1_MOD_WMOIN, IF_REAL, "Width dependence of moin"),
   IOP( "wnoff", FEFET1_MOD_WNOFF, IF_REAL, "Width dependence of noff"),
   IOP( "wvoffcv", FEFET1_MOD_WVOFFCV, IF_REAL, "Width dependence of voffcv"),
   IOP( "wxrcrg1",  FEFET1_MOD_WXRCRG1, IF_REAL, "Width dependence of xrcrg1"),
   IOP( "wxrcrg2",  FEFET1_MOD_WXRCRG2, IF_REAL, "Width dependence of xrcrg2"),
   IOP( "wlambda",  FEFET1_MOD_WLAMBDA, IF_REAL, "Width dependence of lambda"),
   IOP( "wvtl",      FEFET1_MOD_WVTL,     IF_REAL, "Width dependence of vtl"),
   IOP( "wxn",     FEFET1_MOD_WXN,    IF_REAL, "Width dependence of xn"),
   IOP( "weu",  FEFET1_MOD_WEU, IF_REAL, "Width dependence of eu"),
   IOP( "wvfbsdoff",     FEFET1_MOD_WVFBSDOFF,     IF_REAL, "Width dependence of vfbsdoff"),
   IOP( "wtvfbsdoff",     FEFET1_MOD_WTVFBSDOFF,     IF_REAL, "Width dependence of tvfbsdoff"),
   IOP( "wtvoff",     FEFET1_MOD_WTVOFF,     IF_REAL, "Width dependence of tvoff"),

   IOP( "pcdsc",  FEFET1_MOD_PCDSC, IF_REAL, "Cross-term dependence of cdsc"),
   IOP( "pcdscb", FEFET1_MOD_PCDSCB, IF_REAL, "Cross-term dependence of cdscb"), 
   IOP( "pcdscd", FEFET1_MOD_PCDSCD, IF_REAL, "Cross-term dependence of cdscd"),
   IOP( "pcit",   FEFET1_MOD_PCIT,  IF_REAL, "Cross-term dependence of cit"),
   IOP( "pnfactor", FEFET1_MOD_PNFACTOR, IF_REAL, "Cross-term dependence of nfactor"),
   IOP( "pxj", FEFET1_MOD_PXJ, IF_REAL, "Cross-term dependence of xj"),
   IOP( "pvsat", FEFET1_MOD_PVSAT, IF_REAL, "Cross-term dependence of vsat"),
   IOP( "pat", FEFET1_MOD_PAT, IF_REAL, "Cross-term dependence of at"),
   IOP( "pa0", FEFET1_MOD_PA0, IF_REAL, "Cross-term dependence of a0"), 
   IOP( "pags", FEFET1_MOD_PAGS, IF_REAL, "Cross-term dependence of ags"),
   IOP( "pa1", FEFET1_MOD_PA1, IF_REAL, "Cross-term dependence of a1"),
   IOP( "pa2", FEFET1_MOD_PA2, IF_REAL, "Cross-term dependence of a2"),
   IOP( "pketa", FEFET1_MOD_PKETA, IF_REAL, "Cross-term dependence of keta"),
   IOP( "pnsub", FEFET1_MOD_PNSUB, IF_REAL, "Cross-term dependence of nsub"),
   IOP( "pndep",  FEFET1_MOD_PNDEP, IF_REAL, "Cross-term dependence of ndep"),
   IOP( "pnsd",  FEFET1_MOD_PNSD, IF_REAL, "Cross-term dependence of nsd"),
   IOP( "pphin", FEFET1_MOD_PPHIN, IF_REAL, "Cross-term dependence of phin"),
   IOP( "pngate", FEFET1_MOD_PNGATE, IF_REAL, "Cross-term dependence of ngate"),
   IOP( "pgamma1", FEFET1_MOD_PGAMMA1, IF_REAL, "Cross-term dependence of gamma1"),
   IOP( "pgamma2", FEFET1_MOD_PGAMMA2, IF_REAL, "Cross-term dependence of gamma2"),
   IOP( "pvbx", FEFET1_MOD_PVBX, IF_REAL, "Cross-term dependence of vbx"),
   IOP( "pvbm", FEFET1_MOD_PVBM, IF_REAL, "Cross-term dependence of vbm"),
   IOP( "pxt",  FEFET1_MOD_PXT,  IF_REAL, "Cross-term dependence of xt"),
   IOP( "pk1",   FEFET1_MOD_PK1,  IF_REAL, "Cross-term dependence of k1"),
   IOP( "pkt1",  FEFET1_MOD_PKT1, IF_REAL, "Cross-term dependence of kt1"),
   IOP( "pkt1l", FEFET1_MOD_PKT1L, IF_REAL, "Cross-term dependence of kt1l"),
   IOP( "pkt2",  FEFET1_MOD_PKT2, IF_REAL, "Cross-term dependence of kt2"),
   IOP( "pk2",   FEFET1_MOD_PK2,  IF_REAL, "Cross-term dependence of k2"),
   IOP( "pk3",   FEFET1_MOD_PK3,  IF_REAL, "Cross-term dependence of k3"),
   IOP( "pk3b",  FEFET1_MOD_PK3B, IF_REAL, "Cross-term dependence of k3b"),
   IOP( "pw0",   FEFET1_MOD_PW0,  IF_REAL, "Cross-term dependence of w0"),
   IOP( "pdvtp0",  FEFET1_MOD_PDVTP0, IF_REAL, "Cross-term dependence of dvtp0"),
   IOP( "pdvtp1",  FEFET1_MOD_PDVTP1, IF_REAL, "Cross-term dependence of dvtp1"),
   IOP( "plpe0",  FEFET1_MOD_PLPE0, IF_REAL, "Cross-term dependence of lpe0"),
   IOP( "plpeb",  FEFET1_MOD_PLPEB, IF_REAL, "Cross-term dependence of lpeb"),
   IOP( "pdvt0", FEFET1_MOD_PDVT0, IF_REAL, "Cross-term dependence of dvt0"),
   IOP( "pdvt1", FEFET1_MOD_PDVT1, IF_REAL, "Cross-term dependence of dvt1"),
   IOP( "pdvt2", FEFET1_MOD_PDVT2, IF_REAL, "Cross-term dependence of dvt2"),
   IOP( "pdvt0w", FEFET1_MOD_PDVT0W, IF_REAL, "Cross-term dependence of dvt0w"),
   IOP( "pdvt1w", FEFET1_MOD_PDVT1W, IF_REAL, "Cross-term dependence of dvt1w"),
   IOP( "pdvt2w", FEFET1_MOD_PDVT2W, IF_REAL, "Cross-term dependence of dvt2w"),
   IOP( "pdrout", FEFET1_MOD_PDROUT, IF_REAL, "Cross-term dependence of drout"),
   IOP( "pdsub", FEFET1_MOD_PDSUB, IF_REAL, "Cross-term dependence of dsub"),
   IOP( "pvth0", FEFET1_MOD_PVTH0, IF_REAL,"Cross-term dependence of vth0"),
   IOPR("pvtho", FEFET1_MOD_PVTH0, IF_REAL,"Cross-term dependence of vtho"),
   IOP( "pua",  FEFET1_MOD_PUA, IF_REAL, "Cross-term dependence of ua"),
   IOP( "pua1", FEFET1_MOD_PUA1, IF_REAL, "Cross-term dependence of ua1"),
   IOP( "pub", FEFET1_MOD_PUB, IF_REAL, "Cross-term dependence of ub"),
   IOP( "pub1", FEFET1_MOD_PUB1, IF_REAL, "Cross-term dependence of ub1"),
   IOP( "puc",  FEFET1_MOD_PUC, IF_REAL, "Cross-term dependence of uc"),
   IOP( "puc1", FEFET1_MOD_PUC1, IF_REAL, "Cross-term dependence of uc1"),
   IOP( "pud",  FEFET1_MOD_PUD, IF_REAL, "Cross-term dependence of ud"),
   IOP( "pud1", FEFET1_MOD_PUD1, IF_REAL, "Cross-term dependence of ud1"),
   IOP( "pup",  FEFET1_MOD_PUP, IF_REAL, "Cross-term dependence of up"),
   IOP( "plp",  FEFET1_MOD_PLP, IF_REAL, "Cross-term dependence of lp"),
   IOP( "pu0",  FEFET1_MOD_PU0, IF_REAL, "Cross-term dependence of u0"),
   IOP( "pute", FEFET1_MOD_PUTE, IF_REAL, "Cross-term dependence of ute"),
   IOP( "pvoff", FEFET1_MOD_PVOFF, IF_REAL, "Cross-term dependence of voff"),
   IOP( "pminv", FEFET1_MOD_PMINV, IF_REAL, "Cross-term dependence of minv"),
   IOP( "pdelta", FEFET1_MOD_PDELTA, IF_REAL, "Cross-term dependence of delta"),
   IOP( "prdsw", FEFET1_MOD_PRDSW,  IF_REAL, "Cross-term dependence of rdsw "),    
   IOP( "prsw", FEFET1_MOD_PRSW, IF_REAL, "Cross-term dependence of rsw"),
   IOP( "prdw", FEFET1_MOD_PRDW, IF_REAL, "Cross-term dependence of rdw"),

   IOP( "pprwg", FEFET1_MOD_PPRWG,  IF_REAL, "Cross-term dependence of prwg "),    
   IOP( "pprwb", FEFET1_MOD_PPRWB,  IF_REAL, "Cross-term dependence of prwb "),    

   IOP( "pprt", FEFET1_MOD_PPRT, IF_REAL, "Cross-term dependence of prt "),
   IOP( "peta0", FEFET1_MOD_PETA0, IF_REAL, "Cross-term dependence of eta0"),
   IOP( "petab", FEFET1_MOD_PETAB, IF_REAL, "Cross-term dependence of etab"),
   IOP( "ppclm", FEFET1_MOD_PPCLM, IF_REAL, "Cross-term dependence of pclm"),
   IOP( "ppdiblc1", FEFET1_MOD_PPDIBL1, IF_REAL, "Cross-term dependence of pdiblc1"),
   IOP( "ppdiblc2", FEFET1_MOD_PPDIBL2, IF_REAL, "Cross-term dependence of pdiblc2"),
   IOP( "ppdiblcb", FEFET1_MOD_PPDIBLB, IF_REAL, "Cross-term dependence of pdiblcb"),
   IOP( "pfprout", FEFET1_MOD_PFPROUT, IF_REAL, "Cross-term dependence of pdiblcb"),
   IOP( "ppdits", FEFET1_MOD_PPDITS, IF_REAL, "Cross-term dependence of pdits"),
   IOP( "ppditsd", FEFET1_MOD_PPDITSD, IF_REAL, "Cross-term dependence of pditsd"),
   IOP( "ppscbe1",  FEFET1_MOD_PPSCBE1, IF_REAL, "Cross-term dependence of pscbe1"),
   IOP( "ppscbe2",  FEFET1_MOD_PPSCBE2, IF_REAL, "Cross-term dependence of pscbe2"),
   IOP( "ppvag", FEFET1_MOD_PPVAG, IF_REAL, "Cross-term dependence of pvag"),   
   IOP( "pwr",  FEFET1_MOD_PWR, IF_REAL, "Cross-term dependence of wr"),
   IOP( "pdwg", FEFET1_MOD_PDWG, IF_REAL, "Cross-term dependence of dwg"),
   IOP( "pdwb", FEFET1_MOD_PDWB, IF_REAL, "Cross-term dependence of dwb"),
   IOP( "pb0",  FEFET1_MOD_PB0, IF_REAL, "Cross-term dependence of b0"),
   IOP( "pb1",  FEFET1_MOD_PB1, IF_REAL, "Cross-term dependence of b1"),
   IOP( "pcgsl", FEFET1_MOD_PCGSL, IF_REAL, "Cross-term dependence of cgsl"),
   IOP( "pcgdl", FEFET1_MOD_PCGDL, IF_REAL, "Cross-term dependence of cgdl"),
   IOP( "pckappas", FEFET1_MOD_PCKAPPAS, IF_REAL, "Cross-term dependence of ckappas"),
   IOP( "pckappad", FEFET1_MOD_PCKAPPAD, IF_REAL, "Cross-term dependence of ckappad"),
   IOP( "pcf",  FEFET1_MOD_PCF,  IF_REAL, "Cross-term dependence of cf"),
   IOP( "pclc", FEFET1_MOD_PCLC, IF_REAL, "Cross-term dependence of clc"),
   IOP( "pcle", FEFET1_MOD_PCLE, IF_REAL, "Cross-term dependence of cle"),
   IOP( "palpha0", FEFET1_MOD_PALPHA0, IF_REAL, "Cross-term dependence of alpha0"),
   IOP( "palpha1", FEFET1_MOD_PALPHA1, IF_REAL, "Cross-term dependence of alpha1"),
   IOP( "pbeta0", FEFET1_MOD_PBETA0, IF_REAL, "Cross-term dependence of beta0"),

   IOP( "pagidl", FEFET1_MOD_PAGIDL, IF_REAL, "Cross-term dependence of agidl"),
   IOP( "pbgidl", FEFET1_MOD_PBGIDL, IF_REAL, "Cross-term dependence of bgidl"),
   IOP( "pcgidl", FEFET1_MOD_PCGIDL, IF_REAL, "Cross-term dependence of cgidl"),
   IOP( "pegidl", FEFET1_MOD_PEGIDL, IF_REAL, "Cross-term dependence of egidl"),
   IOP( "paigc", FEFET1_MOD_PAIGC, IF_REAL, "Cross-term dependence of aigc"),
   IOP( "pbigc", FEFET1_MOD_PBIGC, IF_REAL, "Cross-term dependence of bigc"),
   IOP( "pcigc", FEFET1_MOD_PCIGC, IF_REAL, "Cross-term dependence of cigc"),
   IOP( "paigsd", FEFET1_MOD_PAIGSD, IF_REAL, "Cross-term dependence of aigsd"),
   IOP( "pbigsd", FEFET1_MOD_PBIGSD, IF_REAL, "Cross-term dependence of bigsd"),
   IOP( "pcigsd", FEFET1_MOD_PCIGSD, IF_REAL, "Cross-term dependence of cigsd"),
   IOP( "paigbacc", FEFET1_MOD_PAIGBACC, IF_REAL, "Cross-term dependence of aigbacc"),
   IOP( "pbigbacc", FEFET1_MOD_PBIGBACC, IF_REAL, "Cross-term dependence of bigbacc"),
   IOP( "pcigbacc", FEFET1_MOD_PCIGBACC, IF_REAL, "Cross-term dependence of cigbacc"),
   IOP( "paigbinv", FEFET1_MOD_PAIGBINV, IF_REAL, "Cross-term dependence of aigbinv"),
   IOP( "pbigbinv", FEFET1_MOD_PBIGBINV, IF_REAL, "Cross-term dependence of bigbinv"),
   IOP( "pcigbinv", FEFET1_MOD_PCIGBINV, IF_REAL, "Cross-term dependence of cigbinv"),
   IOP( "pnigc", FEFET1_MOD_PNIGC, IF_REAL, "Cross-term dependence of nigc"),
   IOP( "pnigbinv", FEFET1_MOD_PNIGBINV, IF_REAL, "Cross-term dependence of nigbinv"),
   IOP( "pnigbacc", FEFET1_MOD_PNIGBACC, IF_REAL, "Cross-term dependence of nigbacc"),
   IOP( "pntox", FEFET1_MOD_PNTOX, IF_REAL, "Cross-term dependence of ntox"),
   IOP( "peigbinv", FEFET1_MOD_PEIGBINV, IF_REAL, "Cross-term dependence for eigbinv"),
   IOP( "ppigcd", FEFET1_MOD_PPIGCD, IF_REAL, "Cross-term dependence for pigcd"),
   IOP( "ppoxedge", FEFET1_MOD_PPOXEDGE, IF_REAL, "Cross-term dependence for poxedge"),
   IOP( "pvfbcv", FEFET1_MOD_PVFBCV, IF_REAL, "Cross-term dependence of vfbcv"),
   IOP( "pvfb", FEFET1_MOD_PVFB, IF_REAL, "Cross-term dependence of vfb"),
   IOP( "pacde", FEFET1_MOD_PACDE, IF_REAL, "Cross-term dependence of acde"),
   IOP( "pmoin", FEFET1_MOD_PMOIN, IF_REAL, "Cross-term dependence of moin"),
   IOP( "pnoff", FEFET1_MOD_PNOFF, IF_REAL, "Cross-term dependence of noff"),
   IOP( "pvoffcv", FEFET1_MOD_PVOFFCV, IF_REAL, "Cross-term dependence of voffcv"),
   IOP( "pxrcrg1",  FEFET1_MOD_PXRCRG1, IF_REAL, "Cross-term dependence of xrcrg1"),
   IOP( "pxrcrg2",  FEFET1_MOD_PXRCRG2, IF_REAL, "Cross-term dependence of xrcrg2"),
   IOP( "plambda",  FEFET1_MOD_PLAMBDA, IF_REAL, "Cross-term dependence of lambda"),
   IOP( "pvtl",      FEFET1_MOD_PVTL,     IF_REAL, "Cross-term dependence of vtl"),
   IOP( "pxn",     FEFET1_MOD_PXN,    IF_REAL, "Cross-term dependence of xn"),
   IOP( "peu",  FEFET1_MOD_PEU, IF_REAL, "Cross-term dependence of eu"),
   IOP( "pvfbsdoff",     FEFET1_MOD_PVFBSDOFF,     IF_REAL, "Cross-term dependence of vfbsdoff"),
   IOP( "ptvfbsdoff",     FEFET1_MOD_PTVFBSDOFF,     IF_REAL, "Cross-term dependence of tvfbsdoff"),
   IOP( "ptvoff",     FEFET1_MOD_PTVOFF,     IF_REAL, "Cross-term dependence of tvoff"),

   /* stress effect*/
   IOP( "saref", FEFET1_MOD_SAREF, IF_REAL, "Reference distance between OD edge to poly of one side"),
   IOP( "sbref", FEFET1_MOD_SBREF, IF_REAL, "Reference distance between OD edge to poly of the other side"),
   IOP( "wlod", FEFET1_MOD_WLOD, IF_REAL, "Width parameter for stress effect"),
   IOP( "ku0", FEFET1_MOD_KU0, IF_REAL, "Mobility degradation/enhancement coefficient for LOD"),
   IOP( "kvsat", FEFET1_MOD_KVSAT, IF_REAL, "Saturation velocity degradation/enhancement parameter for LOD"),
   IOP( "kvth0", FEFET1_MOD_KVTH0, IF_REAL, "Threshold degradation/enhancement parameter for LOD"),
   IOP( "tku0", FEFET1_MOD_TKU0, IF_REAL, "Temperature coefficient of KU0"),
   IOP( "llodku0",  FEFET1_MOD_LLODKU0, IF_REAL, "Length parameter for u0 LOD effect"),
   IOP( "wlodku0",  FEFET1_MOD_WLODKU0, IF_REAL, "Width parameter for u0 LOD effect"),
   IOP( "llodvth",  FEFET1_MOD_LLODVTH, IF_REAL, "Length parameter for vth LOD effect"),
   IOP( "wlodvth",  FEFET1_MOD_WLODVTH, IF_REAL, "Width parameter for vth LOD effect"),
   IOP( "lku0", FEFET1_MOD_LKU0, IF_REAL, "Length dependence of ku0"),
   IOP( "wku0", FEFET1_MOD_WKU0, IF_REAL, "Width dependence of ku0"),
   IOP( "pku0", FEFET1_MOD_PKU0, IF_REAL, "Cross-term dependence of ku0"),
   IOP( "lkvth0", FEFET1_MOD_LKVTH0, IF_REAL, "Length dependence of kvth0"),
   IOP( "wkvth0", FEFET1_MOD_WKVTH0, IF_REAL, "Width dependence of kvth0"),
   IOP( "pkvth0", FEFET1_MOD_PKVTH0, IF_REAL, "Cross-term dependence of kvth0"),
   IOP( "stk2", FEFET1_MOD_STK2, IF_REAL, "K2 shift factor related to stress effect on vth"),
   IOP( "lodk2", FEFET1_MOD_LODK2, IF_REAL, "K2 shift modification factor for stress effect"),
   IOP( "steta0", FEFET1_MOD_STETA0, IF_REAL, "eta0 shift factor related to stress effect on vth"),
   IOP( "lodeta0", FEFET1_MOD_LODETA0, IF_REAL, "eta0 shift modification factor for stress effect"),
   /* Well Proximity Effect */
   IOP( "web", FEFET1_MOD_WEB, IF_REAL, "Coefficient for SCB"),
   IOP( "wec", FEFET1_MOD_WEC, IF_REAL, "Coefficient for SCC"),
   IOP( "kvth0we", FEFET1_MOD_KVTH0WE, IF_REAL, "Threshold shift factor for well proximity effect"),
   IOP( "k2we", FEFET1_MOD_K2WE, IF_REAL, " K2 shift factor for well proximity effect "),
   IOP( "ku0we", FEFET1_MOD_KU0WE, IF_REAL, " Mobility degradation factor for well proximity effect "),
   IOP( "scref", FEFET1_MOD_SCREF, IF_REAL, " Reference distance to calculate SCA, SCB and SCC"),
   IOP( "wpemod", FEFET1_MOD_WPEMOD, IF_REAL, " Flag for WPE model (WPEMOD=1 to activate this model) "),
   IOP( "lkvth0we", FEFET1_MOD_LKVTH0WE, IF_REAL, "Length dependence of kvth0we"),
   IOP( "lk2we", FEFET1_MOD_LK2WE, IF_REAL, " Length dependence of k2we "),
   IOP( "lku0we", FEFET1_MOD_LKU0WE, IF_REAL, " Length dependence of ku0we "),
   IOP( "wkvth0we", FEFET1_MOD_WKVTH0WE, IF_REAL, "Width dependence of kvth0we"),
   IOP( "wk2we", FEFET1_MOD_WK2WE, IF_REAL, " Width dependence of k2we "),
   IOP( "wku0we", FEFET1_MOD_WKU0WE, IF_REAL, " Width dependence of ku0we "),
   IOP( "pkvth0we", FEFET1_MOD_PKVTH0WE, IF_REAL, "Cross-term dependence of kvth0we"),
   IOP( "pk2we", FEFET1_MOD_PK2WE, IF_REAL, " Cross-term dependence of k2we "),
   IOP( "pku0we", FEFET1_MOD_PKU0WE, IF_REAL, " Cross-term dependence of ku0we "),

   IOP( "noia", FEFET1_MOD_NOIA, IF_REAL, "Flicker noise parameter"),
   IOP( "noib", FEFET1_MOD_NOIB, IF_REAL, "Flicker noise parameter"),
   IOP( "noic", FEFET1_MOD_NOIC, IF_REAL, "Flicker noise parameter"),
   IOP( "tnoia", FEFET1_MOD_TNOIA, IF_REAL, "Thermal noise parameter"),
   IOP( "tnoib", FEFET1_MOD_TNOIB, IF_REAL, "Thermal noise parameter"),
   IOP( "rnoia", FEFET1_MOD_RNOIA, IF_REAL, "Thermal noise coefficient"),
   IOP( "rnoib", FEFET1_MOD_RNOIB, IF_REAL, "Thermal noise coefficient"),
   IOP( "ntnoi", FEFET1_MOD_NTNOI, IF_REAL, "Thermal noise parameter"),
   IOP( "em", FEFET1_MOD_EM, IF_REAL, "Flicker noise parameter"),
   IOP( "ef", FEFET1_MOD_EF, IF_REAL, "Flicker noise frequency exponent"),
   IOP( "af", FEFET1_MOD_AF, IF_REAL, "Flicker noise exponent"),
   IOP( "kf", FEFET1_MOD_KF, IF_REAL, "Flicker noise coefficient"),

   IOP("vgs_max", FEFET1_MOD_VGS_MAX, IF_REAL, "maximum voltage G-S branch"),
   IOP("vgd_max", FEFET1_MOD_VGD_MAX, IF_REAL, "maximum voltage G-D branch"),
   IOP("vgb_max", FEFET1_MOD_VGB_MAX, IF_REAL, "maximum voltage G-B branch"),
   IOP("vds_max", FEFET1_MOD_VDS_MAX, IF_REAL, "maximum voltage D-S branch"),
   IOP("vbs_max", FEFET1_MOD_VBS_MAX, IF_REAL, "maximum voltage B-S branch"),
   IOP("vbd_max", FEFET1_MOD_VBD_MAX, IF_REAL, "maximum voltage B-D branch"),
   IOP("vgsr_max", FEFET1_MOD_VGSR_MAX, IF_REAL, "maximum voltage G-S branch"),
   IOP("vgdr_max", FEFET1_MOD_VGDR_MAX, IF_REAL, "maximum voltage G-D branch"),
   IOP("vgbr_max", FEFET1_MOD_VGBR_MAX, IF_REAL, "maximum voltage G-B branch"),
   IOP("vbsr_max", FEFET1_MOD_VBSR_MAX, IF_REAL, "maximum voltage B-S branch"),
   IOP("vbdr_max", FEFET1_MOD_VBDR_MAX, IF_REAL, "maximum voltage B-D branch"),

   IP( "nmos", FEFET1_MOD_NMOS,  IF_FLAG, "Flag to indicate NMOS"),
   IP( "pmos", FEFET1_MOD_PMOS,  IF_FLAG, "Flag to indicate PMOS"),
};

char *FEFET1names[] = {
   "Drain",
   "Gate",
   "Source",
   "Bulk",
   "Charge"
};

int	FEFET1nSize = NUMELEMS(FEFET1names);
int	FEFET1pTSize = NUMELEMS(FEFET1pTable);
int	FEFET1mPTSize = NUMELEMS(FEFET1mPTable);
int	FEFET1iSize = sizeof(FEFET1instance);
int	FEFET1mSize = sizeof(FEFET1model);
